builtinEnter: Object.create / 4
builtinExit: Object.create / 6
builtinEnter: Object.create / 4
builtinExit: Object.create / 6
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:1:1:48:4) / 3
functionEnter: foo / (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:18:1:20:2) / 4
functionExit with exception "this is an exception": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:18:1:20:2) / 3
exception: this is an exception
functionExit with exception "Error: this is an error": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:22:1:24:2) / 3
exception: Error: this is an error
functionExit with exception "undefined": (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:26:1:28:2) / 3
exception: undefined
functionExit: (src/ch.usi.inf.nodeprof.test/js/minitests/exitException.js:1:2:48:2) / 3
[ 'Object.create', 'foo' ]
